"""
LifeRoute AI — Referral Document Agent
Generates a structured markdown referral document via OpenRouter.
"""

from graph.llm_client import chat_completion

REFERRAL_PROMPT = """You are a medical referral document generator for LifeRoute AI. Generate a professional, structured referral summary document.

CRITICAL RULES:
- NEVER state a diagnosis. Use "symptoms suggest...", "presentation consistent with..."
- This document accompanies the patient to the hospital
- Be professional but accessible — the patient and receiving doctor will both read this
- Respond in the SAME LANGUAGE as the patient's original input (English or Hindi)
- Format the document in clean markdown

Generate the referral document in this structure:

# LifeRoute AI — Patient Referral Summary

**Date:** [current date]
**Referral ID:** LR-[random 6 digits]

## Patient Presentation
[Chief complaint, duration, severity, associated symptoms]

## Triage Assessment
**Urgency Level:** [level]
[Reasoning — cautious language, no diagnosis]

## Recommended Facility
**Hospital:** [name]
**Address:** [address]
**Contact:** [phone]

### Why This Facility
[Routing reason — why this hospital is the best match]

## Recommended Next Steps
[3-4 bullet points of what the patient should do]

---
*This referral was generated by LifeRoute AI and is for navigation guidance only. It is not a substitute for professional medical evaluation.*"""


def referral_agent(state: dict) -> dict:
    """Generate a structured referral document."""

    language = state.get("language", "en")
    symptoms = state["structured_symptoms"]
    triage_level = state["triage_level"]
    triage_reasoning = state["triage_reasoning"]
    facility = state["selected_facility"]
    routing_reason = state["routing_reason"]

    context = f"""Patient Information:
- Language: {language}
- Chief Complaint: {symptoms.get('chief_complaint', 'Not specified')}
- Duration: {symptoms.get('duration', 'Not specified')}
- Severity: {symptoms.get('severity', 'Not specified')}/10
- Associated Symptoms: {', '.join(symptoms.get('associated_symptoms', [])) or 'None reported'}
- Age: {symptoms.get('age', 'Not specified')}
- Gender: {symptoms.get('gender', 'Not specified')}

Triage Assessment:
- Level: {triage_level.upper()}
- Reasoning: {triage_reasoning}

Recommended Facility:
- Hospital: {facility.get('name', 'Not available')}
- Address: {facility.get('address', 'Not available')}
- City: {facility.get('city', 'Not available')}
- Contact: {facility.get('contact', 'Not available')}
- Specialties: {', '.join(facility.get('specialties', []))}

Routing Reason: {routing_reason}

Original patient input: "{state.get('raw_input', '')}"
"""

    try:
        lang_instruction = ""
        if language == "hi":
            lang_instruction = "\n\nIMPORTANT: Write the referral document in Hindi (Devanagari script), except for medical terms, hospital names, and the header which should remain in English."

        referral_doc = chat_completion(
            f"{REFERRAL_PROMPT}{lang_instruction}\n\n{context}",
            max_tokens=1000,
        )

        return {"referral_doc": referral_doc}

    except Exception as e:
        print(f"[Referral Agent] Error: {e}")
        fallback = f"""# LifeRoute AI — Patient Referral Summary

**Urgency Level:** {triage_level.upper()}

## Patient Presentation
{symptoms.get('chief_complaint', 'Symptoms reported by patient')}

## Triage Assessment
{triage_reasoning}

## Recommended Facility
**Hospital:** {facility.get('name', 'Please consult nearest facility')}
**Address:** {facility.get('address', 'N/A')}
**Contact:** {facility.get('contact', 'N/A')}

## Recommended Next Steps
- Proceed to the recommended facility as soon as possible
- Bring any current medications and medical records
- If symptoms worsen, call emergency services (112)

---
*This referral was generated by LifeRoute AI and is for navigation guidance only.*"""

        return {"referral_doc": fallback}
